### PR TITLE
Sprite height/width @setters

### PR DESCRIPTION
**Pull request by jej**
In the app I am coding, I need to work with pixel sizes, not with scale. Seems to work now like this:

```
sprite = pyglet.sprite.Sprite(img=image)
sprite.width = 1920
sprite.height = 1440
```
Currently width/height are read-only.

### CODE REVIEW

**Comment by gran4** [comment]
I don't think there is a case where _scale is negitive, is there?

**Comment by pushfoo** [comment]
> I don't think there is a case where _scale is negitive, is there?

There is. Negative scale is a quick way of mirroring along the X and Y axes, or only one axis if you only alter scale for one dimension.

The downside is that it produces negative apparent widths if handled naively. Using `abs` ensures meaningful return values which can be used for layout and packing.

**Comment by jej** [comment]
I just used the formula to get width from scale:

```
width = self._texture.width * abs(self._scale_x) * abs(self._scale)
```
to get the scale from width (or height). As said by @pushfoo, a negative scale/width (or height) mirror the sprite.

**Review by benmoran56 — APPROVED** [review]

**Comment by benmoran56** [comment]
This looks like a reasonably useful change, and doesn't break anything. Thanks for the PR.

**Pull request merged**
