### PR TITLE
[WIP] Auto Reposition Frame for #821

### PR DESCRIPTION
**Pull request by shenjackyuanjie**
the Pull Request for #821

### CODE REVIEW

**Comment by shenjackyuanjie** [comment]
hello?
anyone here?

**Comment by benmoran56** [comment]
Hi @shenjackyuanjie,  sorry for the delay. 

How about implementing this as a subclass of Frame?  That way, the spacial hash can be used.

**Comment by shenjackyuanjie** [comment]
> How about implementing this as a subclass of Frame? That way, the spacial hash can be used.

Hmmmmm, I add the `hash` here just for indexing the widget/shape so that you can add/remove widget/shape with a `hash`, witch spacial hash are you talking about? if it is the hash used by `Frame`. I do not think it will have a good performance ( after all it will remove and add all the widget/shape when resizing)

I do think make this a subclass of `Frame` is a good idea, but it will require many modify in `Frame` class. sence the `Frame` have some unuse function for the reposition frame

(BTW, @jason-bowen-zheng and I is think about make this function just like the tkinker's `grid` function, but it will be a hard time to do it

**Comment by shenjackyuanjie** [comment]
So I change it to draft with WIP
let's see if this PR can become better

**Comment by shenjackyuanjie** [comment]
I still think this PR is just an WIP one
just that I'm not sure how to implment it

**Pull request closed without merging**
