### PR TITLE
Update events.py to use KeyStateHandler 

### PR DESCRIPTION
**Pull request by Hibot12**
Now KeyStateHandler is used, instead of the 'old' approach.

### CODE REVIEW

**Comment by DoAltPlusF4** [comment]
Window events are not an "old" approach. It entirely depends on what you are trying to do.
Keep in mind that the KeyStateHandler uses events itself to track input. 
(https://github.com/pyglet/pyglet/blob/c32556e92e854b9001da39fba70c4deb63c28878/pyglet/window/key.py#L67)

The events.py example is meant to be an example of events anyway, not the KeyStateHandler.

**Comment by benmoran56** [comment]
I agree. The KeyStateHandler is more of a generic thing, for convenience. For advanced uses, you want to use the event system directly.

We could add a separate example just for the KeyStateHandler though.

**Comment by Hibot12** [comment]
I think creating another example would be great for new users. Definitely should do it.

**Comment by Hibot12** [comment]
I will open another PR for this.

**Pull request closed without merging**
