### PR TITLE
Improvements to pyglet.gui

### PR DESCRIPTION
**Pull request by jason-bowen-zheng**
This PR didn't add any features to pyglet.

Instead, `Frame` can change its cell info when widgets change their position, which wasn't implemented before.

Also, users can choose to enable or disable a frame.

### CODE REVIEW

**Comment by benmoran56** [comment]
I had some ideas about this. Rather than coupling frame and widgets, how about using events? 
BaseWidget could dispatch a new event, like `on_reposition`.  It can dispatch this event whenever you change the x, y, or position. When you add a Widget to a Frame, the Frame can register this event.

For example, in the Widget:
```py
# WidgetBase
    @position.setter
    def position(self, values):
        self._x, self._y = values
        self._update_position()
        self.dispatch_event('on_reposition', self)
```
And in the Frame:
```py
    def _on_reposition_handler(self, widget):
        ...

    def add_widget(self, widget):
        """Add a Widget to the spatial hash."""
        min_vec, max_vec = self._hash(*widget.aabb[0:2]), self._hash(*widget.aabb[2:4])
        for i in range(min_vec[0], max_vec[0] + 1):
            for j in range(min_vec[1], max_vec[1] + 1):
                self._cells.setdefault((i, j), set()).add(widget)
        widget.update_groups(self._order)
        widget.set_handler('on_reposition', self._on_reposition_handler)
```

Frame disable is a good idea. Actually, I thought about separating `Window` and `Frame` entirely. 
Currently, you have to pass a Window instance to Frame. I think it might be better to make it explicit. For example:
```py
my_frame = Frame()
window.push_handlers(my_frame)
```
That way, you can just set or remove the events at any time. Extra code doesn't need to be added to the Frame class.

**Comment by jason-bowen-zheng** [comment]
About the first idea, unluckly, it won't work **now** because of the strange hehavior of `Frame.remove_widget`. But, I can rewrite the code of `remove_widget`.

In my opinion, I refuse to accept your second idea for:

> (Assume we have clear docs and a beginner read it) `Frame.enable` is meaningful, which shows this property control the enable or disable state of frame.

Using `Frame.enable` is clear, direct and easy to understand!

**Comment by benmoran56** [comment]
Widget changes look good. Thanks! 

One thing I noticed. Is it necessary to do: 
```py
        if not self._enable:
            return
            ....
```
When setting enable = False,  we have already called `window.remove_handlers`. The events should not reach the handlers anymore.

**Comment by benmoran56** [comment]
Looks good! 

There is one final consideration.  Adding `enable` property/setter is OK, because it's backwards compatible. We can merge this directly into the master branch. 

If we add `enable=True` to `__init__`, then it changes the API. If we do that, we should target pyglet 2.1 (the `development` branch). 

We have two options: 
1. Change target from master -> development.  The code is OK as-is. 
2. Remove the `enable=True` from `__init__`, and merge into master. (You can also make a separate PR for `development`, which includes the `enable=True`). 

What do you think?

**Comment by jason-bowen-zheng** [comment]
Thanks for your advice, I have changed it.

**Comment by jason-bowen-zheng** [comment]
I choose option 1, but I don't know how to do it.

Should I reopen a PR?

**Review by benmoran56 — APPROVED** [review]
Looks good to go.

**Comment by benmoran56** [comment]
Merged!  I was able to do it through Github by changing the target. 

One small change:  For consistency, I will rename `enable` to `enabled`. This grammatical change will match other pyglet objects, such as `Sprite.paused`.

**Pull request merged**
