### PR TITLE
Added QoL properties to ScissorGroup.

### PR DESCRIPTION
**Pull request by DoAltPlusF4**
Added some quality of life properties to the ScissorGroup class at `examples/opengl_scissor.py`.
These include X, Y, width, and height.

### CODE REVIEW

**Comment by benmoran56** [comment]
Thanks for the pull request. The reason I didn't make these attributes public, was because it might cause confusion if they are changed. If two groups are created with the same area, they will be consolidated internally: 
```py
groupa = ScissorGroup(10, 10, 100, 100)
groupb = ScissorGroup(10, 10, 100, 100)
groupa == groupb   # True
```
If you then change the area these groups, only one of them will actually have any effect (as the other one is discarded internally, and not used when drawing). 

We could dump the hash/eq methods so that different instances of this group are not consolidated. 
It would avoid issues like this, but would cause performance issues if someone were to create multiple instances of the same Group instead of reusing the same instance. Maybe that would be better though.

**Comment by DoAltPlusF4** [comment]
Hmm, I didn't think about that. :/

As an end-user, I would probably prefer it if they stayed as separate instances, though I'm not 100% sure on the performance implications of this.

**Comment by DoAltPlusF4** [comment]
I also realise that I accidentally added another commit (Anchor constants to `pyglet.text`), this was by mistake, do you know how I should remove it? (My fault for not making a separate branch for it :P )

**Comment by benmoran56** [comment]
If you're just going to make a few, then there won't be any performance problem. The problems arise if you try to do something like this: 
```py
for i in range(tile_width):
    group = ScissorGroup(10, 10, 100, 100)
    sprite = Sprite(....group=group)
```
For something like `OrderedGroup(order)` that pattern is fine, since they don't change and can get consolidated together internally. Without the hash/eq methods, however, you would end up with every single Sprite instance being in a separate Group, and hence a separate internal draw call. The solution is to do something like this: 
```py
group = ScissorGroup(10, 10, 100, 100)
for i in range(tile_width):
    sprite = Sprite(....group=group)
```
That way you have only a single Group instance, so eq/hash methods don't come into play since no consolidation will happen. 


As for the stray commit, I think the only thing you can do is to revert the file back the way it was an commit again. Other than that I'm not sure.

**Comment by benmoran56** [comment]
Since this Group can't be consolidated if the scissor area is different, maybe we just dump the hash/eq methods, and just expose x, y, width, height attributes directly. It will simplify the class, and won't need the extra properties.

In that case we should also write in the docstring that you should use the same exact instance for all objects that will be in the group, and not make a new instance each time. What do you think?

**Comment by DoAltPlusF4** [comment]
Sounds good 👍

**Comment by benmoran56** [comment]
How about dropping all of the properties/setters, and just exposing `x, y, width, height` attributes directly?

**Comment by DoAltPlusF4** [comment]
I removed the `x`, `y`, `width` and `height` properties in favour of exposing them directly.
I also added an `area` property.

**Comment by benmoran56** [comment]
Thanks!

**Pull request merged**
