### PR TITLE
Add Bezier curve

### PR DESCRIPTION
**Pull request by jason-bowen-zheng**
I have created a `pyglet.shapes.BezierCurve` class for Bézier curve.

There is an example:
```python
import pyglet
from pyglet import shapes

window = pyglet.window.Window(300, 300)
curve = shapes.BezierCurve((100, 100), (150, 200), (200, 100), segments=10)
line = [
    shapes.Line(100, 100, 150, 200, color=(255, 0, 0)),
    shapes.Line(150, 200, 200, 100, color=(255, 0, 0))
]

@window.event
def on_draw():
    window.clear()
    curve.draw()
    for obj in line:
        obj.draw()

pyglet.app.run()
```

But it still has some problems, as the picture showed:
problem0

And the points generated by the curve formula(the `_make_curve` method) seems correct:
```
[(100.0, 100.0), (110.0, 118.0), (120.0, 132.0), (130.0, 142.0), (140.0, 148.0), (150.0, 150.0), (160.0, 148.0), (170.0, 142.0), (180.0, 132.0), (190.0, 118.0), (200.0, 100.0)]
```

Another example:
problem1

### CODE REVIEW

**Comment by benmoran56** [comment]
Thank you for the pull request.

I think I found the bug.
In most shapes, the user is setting the x, y coordinates when creating the Shape. For others Shapes, like Polygon, the user is supplying their own coordinates directly. When creating the VertexList, the polygon is doing this to normalize all points to 0: 
```py
            trans_x, trans_y = self._coordinates[0]
            trans_x += self._anchor_x
            trans_y += self._anchor_y
            coords = [[x - trans_x, y - trans_y] for x, y in self._coordinates]
```
Does that make sense?

**Comment by jason-bowen-zheng** [comment]
Thank you for the advice, it works well now.

**Comment by benmoran56** [comment]
Thanks Jason!

**Review by benmoran56 — APPROVED** [review]

**Comment by shenjackyuanjie** [comment]
\o/
恭喜PR(

**Comment by jason-bowen-zheng** [comment]
@shenjackyuanjie 我是真没想到一个简简单单的PR被合并并且关闭之后还有人评论。

要不阁下也继续为pyglet贡献一点东西（比如说3D支持）？

**Comment by shenjackyuanjie** [comment]
在写了在写了
以及反正闲的没事在逛github，看看pyglet有没有新commit
最近DR就在给pyglet造widget的轮子，说不定啥时候就给pyglet加进来
3D支持一直有啊，只不过得直接操控GL（
（其实我比较期待2.1 release之后关于vulkan的支持的决议

**Comment by shenjackyuanjie** [comment]
哦对了，我正好在想给widget/shape加一个自动重定位的功能
就是你提供一个函数，on_resize的时候自动调用他，同时你在初始化的时候就用这个函数设置位置
这样 可以重设窗口大小的widget就不用在on_resize里给每一个部件重设位置了

**Comment by jason-bowen-zheng** [comment]
感谢您***将来***对pyglet的贡献。

不过，这是一个已经结束的PR，您如此发言是不太适合的（见下方HTML注释），除非该PR中的内容有问题。


我认为阁下所构想的重定位非常有吸引力，这可以让我的大脑远离一部分数学计算。

不过，这样一个通用的方法实现起来必然是麻烦的，您能做到像[这个on_resize一样](https://github.com/Minecraft-in-python/Minecraft/blob/3d4e9a870f5b1b99b01712d72b72558b06952fbe/minecraft/scene/start.py#L103)，使各个部件的相对位置不变且不会重合吗？

情况千变万化，最原始的方法（设置`x`、`y`、`width`、`height`）说不定是最好的方法哦。

**Comment by pushfoo** [comment]
I'm relying on machine translation, so I apologize in advance if I misunderstood. Are you planning to add resize handling to the base classes in pyglet in addition to the handler in the project you linked? If you plan to add it to pyglet, we should probably move discussion to a new issue.

**Comment by jason-bowen-zheng** [comment]
@pushfoo I think you were misunderstood. We will not discuss anything later in this PR. And @shenjackyuanjie will open a PR or an issue about the feature at any time.

**Pull request merged**
