### PR TITLE
Skip functions marked as OBJC_ARM64_UNAVAILABLE.

### LINKED ISSUE #331: macOS M1 BigSur 11.1 rendering problem
On macos Bigsur 11.1, python 3.8.2, after upgrading to pyglet==1.5.11, when running openai's gym env.render() I get the error: 

```File ".../python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File ".../python3.8/site-packages/pyglet/gl/__init__.py", line 234, in <module>
    from .cocoa import CocoaConfig as Config
  File ".../python3.8/site-packages/pyglet/gl/cocoa.py", line 44, in <module>
    from pyglet.canvas.cocoa import CocoaCanvas
  File ".../python3.8/site-packages/pyglet/canvas/__init__.py", line 102, in <module>
    from pyglet.canvas.cocoa import CocoaDisplay as Display
  File ".../python3.8/site-packages/pyglet/canvas/cocoa.py", line 41, in <module>
    from pyglet.libs.darwin.cocoapy import CGDirectDisplayID, quartz, cf
  File ".../python3.8/site-packages/pyglet/libs/darwin/__init__.py", line 36, in <module>
    from .cocoapy import *
  File ".../python3.8/site-packages/pyglet/libs/darwin/cocoapy/__init__.py", line 32, in <module>
    from .runtime import objc, send_message, send_super
  File ".../python3.8/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 133, in <module>
    objc.class_getMethodImplementation_stret.restype = c_void_p
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1045f9aa0, class_getMethodImplementation_stret): symbol not found```

### PR DESCRIPTION
**Pull request by mahiuchun**
This should fix #331 and #334.

Objective-C runtime source code could be seen here: https://opensource.apple.com/tarballs/objc4/

### CODE REVIEW

**Comment by antic11d** [comment]
@mahiuchun Any estimated time on when will this be merged/released?

**Review by benmoran56 — APPROVED** [review]

**Comment by benmoran56** [comment]
Merged, right now :) 

I'll try to get a point release out as soon as possible. Hopefully today or tomorrow. 
In the mean time, if you're using pip, you could upgrade directly from the repository with something like: 
`pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance`

Thank you very much for the pull request @mahiuchun!

**Comment by zxnuli** [comment]
thx :-)

**Comment by Malloc-Lu** [comment]
> Merged, right now :)
> 
> I'll try to get a point release out as soon as possible. Hopefully today or tomorrow. In the mean time, if you're using pip, you could upgrade directly from the repository with something like: `pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance`
> 
> Thank you very much for the pull request @mahiuchun!

I input the command in my terminal, but there is not any replying.
My environment is macos 13, apple silicon. How can I fix it?

**Comment by Malloc-Lu** [comment]
Fine, I have solved it with installing pyglet==1.5.15 luckly.

**Pull request merged**
