### PR TITLE
Label and Layout enhancements

### PR DESCRIPTION
**Pull request by caffeinepills**
This adds a couple enhancements to existing Label and layouts to make it similar to Sprites.

Adds a visibility property. This behaves like Sprite visibility, except this deletes the vertices, then re-adds them. This also lets you change text while it's not visible.

Add opacity property for DocumentLabels. - Even though you can adjust this through color property, it gets cumbersome if all you want to do is adjust the opacity.

Add an update function to update both the x and y position simultaneously on layouts. This is a small performance speedup, since both axis can be adjusted in the same loop. In the future can be added with more functionality, for example, adding a Z axis or rotations.

### CODE REVIEW

**Comment by jason-bowen-zheng** [comment]
Can I rotate the Label?

**Review by benmoran56 — APPROVED** [review]
Thanks! These were definitely lacking.

**Comment by benmoran56** [comment]
@jason-bowen-zheng Unfortunately not.  The layout class it too complex to add rotation. 
Instead, it would be better to create a Texture out of a Label, and then rotate that. 
Eventually we need to add an example to the Github on how to do that.

**Comment by jason-bowen-zheng** [comment]
@benmoran56 It seems like a good solution!

**Comment by caffeinepills** [comment]
> Can I rotate the Label?

Not with this merge. However, this is supported in the alternate font renderer (Windows only).

See: https://github.com/pyglet/pyglet/blob/pyglet-1.5-maintenance/examples/text/advanced_font.py

**Pull request merged**
