### PR TITLE
Fix "sticky buttons"

### LINKED ISSUE #681: add on_activate event to KeyStateHandler
Please add on_activate event to KeyStateHandler, with reset to data dict(setting the data dict to a new empty one), because when you leave the window and you holded down a key then when you release it its still holded down, and the only way to stop it is to press the key once

### PR DESCRIPTION
**Pull request by LennyPhoenix**
This PR makes 2 changes:

- Adds the `on_deactivate` event to the mouse and key state handlers, meaning that when the window loses focus it will treat it like all keys and mouse buttons had just been released. This prevents issues with "sticky buttons" such as when alt+tabbing when holding a key down.
- Imports the `pyglet.window.mouse` module by default.

Resolves #681

### CODE REVIEW

**Comment by caffeinepills** [comment]
Doesn't this just create an issue with the reverse? If I hold a key down, alt tab, then tab back, it's no longer treated as being held down?

**Comment by csd4ni3l** [comment]
but already if someone holds down a key in that window and tab to another one why would they want it to be holded down in that window too?

**Comment by LennyPhoenix** [comment]
> Doesn't this just create an issue with the reverse? If I hold a key down, have the window lose focus, then tab back, it's no longer treated as being held down even though the key is?

I'd personally rather have the key release itself than it appear stuck, in most games having a key stuck is going to lead to more annoyance than just having it no-longer pressed.

I'm just not sure how we would fix an issue like this, is there a way to detect keyboard events even when the window is not focused? The only way I can see a full solution to this is keeping track of key presses even when unfocused, then checking if the window is active in `__getitem__` (probably with some flag set by `on_activate` and `on_deactivate`)

**Review by benmoran56 — APPROVED** [review]

**Comment by benmoran56** [comment]
Thank you Lenny!

**Pull request merged**
