### PR TITLE
Pyglet 1.0 maintenance

### PR DESCRIPTION
**Pull request by planetbyter**
pip install pyglet

### CODE REVIEW

**Comment by benmoran56** [comment]
Hello, 
Your pull request is attempting to merge changes from the 1.0-maintenance branch into master.
Are you indeeding attempting to update the 1.0 branch? If so, could I ask what the use case is? This branch has long been unsupported.

**Comment by DoAltPlusF4** [comment]
Yeah... I don't think merging changes from 2008 is really a good idea...

**Comment by benmoran56** [comment]
I'm going to close this due to lack of reply (and other potential issues). If you read this, and want to give it another try, please update here or open a new PR. 
Thanks!

**Comment by bl-ue** [comment]
Why isn't this closed?  It's likely just an experiment.  @planetbyter didn't even write the PR title; GitHub generated it based on the name of branch.

**Comment by benmoran56** [comment]
When I tried to close this initially, it also had the side effect of deleting the 1.0 branch. It seems like this might have been a GitHub bug of some sort.

Realistically though, these extremely old branches probably don't need to be kept around anymore. There is no chance of anyone doing any maintenance releases for such old releases, since they don't work anymore on supported Python and modern OSs.

**Comment by bl-ue** [comment]
>When I tried to close this initially, it also had the side effect of deleting the 1.0 branch. It seems like this might have been a GitHub bug of some sort.

Weird.  Well you may be able to restore the branch if it gets deleted, but 🤷🏻‍♂️

**Comment by LennyPhoenix** [comment]
You should just be able to push the branch from your local repo if it tries to delete branch

**Comment by bl-ue** [comment]
Also, GH lets you restore branches when you delete them, I think even right from the PR's page itself.

**Comment by benmoran56** [comment]
Looks like I was able to close it this time _without_ it automatically deleting the branch. 
Thanks guys!

**Pull request closed without merging**
