### PR TITLE
Make Widget repositionable

### PR DESCRIPTION
**Pull request by shenjackyuanjie**
Added DragSprite to `pyglet.gui.widgets`
need more test not done
and need to make it more standardized)

testing translate the docs (just testing, you can don't merge the first commit)
(咕 means lazy

### CODE REVIEW

**Comment by benmoran56** [comment]
To follow up on your conversation on Discord, I will write down some ideas we talked about. 

I think it makes sense to allow ALL Widgets to be re-positioned. 
If we do that, then it becomes easier to implement some of your advanced ideas. 
To start we would need to do the following: 
1. When adding a Widget to a Frame, the frame instance should be set on the Widget:  
`widget.frame = self`
(This will be useful later). 
2. Widgets should have a `x` & `y` setters (and also a `position` property/setter for convenience). 

If you reposition a Widget, it will break the spatial hashing in the Frame. 
For that reason, Widgets will need to be removed/re-added to the Frame if you reposition them. 

What do you think?

**Comment by shenjackyuanjie** [comment]
> To follow up on your conversation on Discord, I will write down some ideas we talked about.
> 
> I think it makes sense to allow ALL Widgets to be re-positioned.
> If we do that, then it becomes easier to implement some of your advanced ideas.
> To start we would need to do the following:
> 
> 1. When adding a Widget to a Frame, the frame instance should be set on the Widget:
>    `widget.frame = self`
>    (This will be useful later).
> 2. Widgets should have a `x` & `y` setters (and also a `position` property/setter for convenience).
> 
> ‎如果您重新定位小部件‎, it will break the spatial hashing in the Frame.
> For that reason, Widgets will need to be removed/re-added to the Frame if you reposition them.
> 
> What do you think?

hmmm it's a good idea of reposition all widget
i read the source code of frame class , and i found that frame will first check if the hit hits the wigets
so that will be duble hit check when click, so maybe we can remove frame's hit check to make it faster]
and also it will make re-add to the Frame no needed

sorry for my responce are so late , i have school now , and the 'frame' are mostly 'Frame'

i will give a other commit later this week (maybe this , or next) about wiget and Frame

**Comment by shenjackyuanjie** [comment]
sorry i push my own projec's commit name with pyglet's commit

**Comment by benmoran56** [comment]
Do you mean:
```py
for widget in self._cells.get(self._hash(x, y), set()):
```
The Frame uses a "Spatial Hash" - this is necessary for performance. It's not possible to use a very large number of Widgets without a Spatial Hash. That is the main reason for the existence of the Frame.

**Comment by jason-bowen-zheng** [comment]
@shenjackyuanjie 我亲爱的~~鸽子~~同胞, 您改写的函数定义: `foo(args: type)` 不符合 pyglet 其余函数定义, 这里希望你改正. 另, 请仔细阅读 READNE, 不要在 `master` 下更改, 切换到 `pyglet-1.5-maintenance` 分支下更改再发布 PR:
```bash
git checkout pyglet-1.5-maintenance
# 一些操作
git push
```
如果是一个可以拖动的 `Sprite`, 何不在其本身上设置 `can_drag` 参数以控制其可否拖动?

> `pyglet.gui` 真的非常差劲, [`minecraft.gui`](https://github.com/Minecraft-in-python/Minecraft/tree/master/minecraft/gui) 在其基础上改造升华了, 到我想好了如果为 pyglet 编写更好的 GUI 时我会开 PR 的.

**Comment by shenjackyuanjie** [comment]
> @shenjackyuanjie 我亲爱的~鸽子~同胞, 您改写的函数定义: `foo(args: type)` 不符合 pyglet 其余函数定义, 这里希望你改正. 另, 请仔细阅读 READNE, 不要在 `master` 下更改, 切换到 `pyglet-1.5-maintenance` 分支下更改再发布 PR:
> 
> ```shell
> git checkout pyglet-1.5-maintenance
> # 一些操作
> git push
> ```
> 
> 如果是一个可以拖动的 `Sprite`, 何不在其本身上设置 `can_drag` 参数以控制其可否拖动?
> 
> > `pyglet.gui` 真的非常差劲, [`minecraft.gui`](https://github.com/Minecraft-in-python/Minecraft/tree/master/minecraft/gui) 在其基础上改造升华了, 到我想好了如果为 pyglet 编写更好的 GUI 时我会开 PR 的.

首先，我觉得pyglet的gui已经做得很好了（
然后，我就是为了2.0去做更新的，所以就在master，1.5尽量会回滚，但是discord上已经说了专注于2.0开发了，所以····
然后，foo(args: type)嘛·····（我愿意（（（（（

**Comment by jason-bowen-zheng** [comment]
`pyglet.gui` 我认为是不错的, 但很显然比起其他的 pyglet GUI 库还差了一些, 还是有很多 GUI 部件可以添加的(这个我会稍\~后\~开PR(同为鸽子)). 至于1.5与2.0的区别嘛, 不是一点点, 毕竟 `pyglet.gui` 已经非常高级了. 而且现有的 pyglet 的子模块只有2D图形库的一些功能, 可否建议增加三维相关功能?

鄙人最近正在尝试将动画运用到 `pyglet.shapes`, `pyglet.sprite` 以及 `pyglet.text` 的对象中.
> 以后可否用英语交谈? 毕竟参与该项目的贡献者大部分使用英语(你英语不是很好吧).

**Comment by shenjackyuanjie** [comment]
> `pyglet.gui` 我认为是不错的, 但很显然比起其他的 pyglet GUI 库还差了一些, 还是有很多 GUI 部件可以添加的(这个我会稍~后~开PR(同为鸽子)). 至于1.5与2.0的区别嘛, 不是一点点, 毕竟 `pyglet.gui` 已经非常高级了. 而且现有的 pyglet 的子模块只有2D图形库的一些功能, 可否建议增加三维相关功能?
> 
> 鄙人最近正在尝试将动画运用到 `pyglet.shapes`, `pyglet.sprite` 以及 `pyglet.text` 的对象中.
> 
> > 以后可否用英语交谈? 毕竟参与该项目的贡献者大部分使用英语(你英语不是很好吧).

主要是这些话都是跟你说的，如果有项目相关的信息我会用英语的，我想问的是，你对待你名下的github项目，plan.md是认真的吗？
`pyglet.gui`的gui确实可以加很多，就看你了

**Comment by jason-bowen-zheng** [comment]
No, I won't add any widget. A button have a `pressed` image, a `depressed` image, a `hover` image: toooo many images! Can we use a set of shapes to replace a image, or replaced with some sprites? Or we can let developer choose.
> 您的对话很显然就不符合下面那行小字中 [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines) 的 `清楚明确, 紧靠主题` 一项.



^ 以上已经回答了你的问题(有不表示存在) ^

**Comment by benmoran56** [comment]
I have added the ability to change the position to the Widget base class. 
In addition, I have created a new `Frame` subclass. You can have a look here: 
https://github.com/pyglet/pyglet/blob/master/pyglet/gui/frame.py#L133

This is just an example, using a key modifier (ALT, CTRL, etc.) to allow dragging a Widget. 
Instead of using key modifiers, a custom class can be made for other conditions.

**Comment by shenjackyuanjie** [comment]
hommm
i'think this PR can be close

**Pull request closed without merging**
