### PR TITLE
Fix issue #274

### LINKED ISSUE #274: Import Error: Can't find framework %s." % path
When I try to run `from pyglet.gl import *`

The code line 262 tries to find OpenGL inside the directory `/System/Library/Frameworks/OpenGL.framework`. 
https://github.com/pyglet/pyglet/blob/d563b7a001506758a77fde035c22c786476d0093/pyglet/lib.py#L262
The function `return None` which in turn `raise ImportError("Can't find framework %s." % path) # on line 283`

-----
**System Information**

OS: Mac OS Big Sur Public 11.0 Beta (20A5354i).

```sh
Darwin Akarshs-MacBook-Pro.local 20.0.0 Darwin Kernel Version 20.0.0: Fri Aug 14 00:25:13 PDT 2020; root:xnu-7195.40.44.151.1~4/RELEASE_X86_64 x86_64
```

Tree structure of the dir `/System/Library/Frameworks/OpenGL.framework` in my system. 
```sh
 akarshjain@Akarshs-MacBook-Pro  /System/Library/Frameworks/OpenGL.framework  tree 
.
├── Libraries -> Versions/Current/Libraries
├── Resources -> Versions/Current/Resources
└── Versions
    ├── A
    │   ├── Libraries
    │   │   ├── 3425AMD
    │   │   │   ├── CVMCompiler
    │   │   │   └── libCoreVMClient.mono.dylib
    │   │   ├── 3600
    │   │   │   ├── CVMCompiler
    │   │   │   └── libCoreVMClient.mono.dylib
    │   │   ├── CVMCompiler
    │   │   ├── CVMServer
    │   │   ├── DumpGPURestart
    │   │   ├── ReportGPURestart
    │   │   ├── libGLVMPlugin.dylib
    │   │   ├── libGLVMPlugin31001.dylib
    │   │   ├── libGLVMPlugin3802.dylib
    │   │   └── libGLVMPlugin3902.dylib
    │   ├── Resources
    │   │   ├── BridgeSupport
    │   │   │   └── OpenGL.bridgesupport
    │   │   ├── CVMSPlugin.exp
    │   │   ├── CVMSPluginAll.exp
    │   │   ├── CVMSPluginNoExec.exp
    │   │   ├── GLByteCodes.arm64.bc
    │   │   ├── GLByteCodes.x86_64.bc
    │   │   ├── GLEngine.bundle
    │   │   │   └── GLEngine
    │   │   ├── GLRendererFloat.bundle
    │   │   │   └── GLRendererFloat
    │   │   ├── Info.plist
    │   │   ├── cvmsConfig.plist
    │   │   └── version.plist
    │   └── _CodeSignature
    │       └── CodeResources
    └── Current -> A

```

### PR DESCRIPTION
**Pull request by jerekshoe**
This should fix #274. This is still broken when using official python releases, but the version of python bundled with the macOS 11 Beta (a modified version of 3.8.2) has fixes for some of the issues caused by changes in Big Sur. The appropriate version of python should be found in `/usr/bin/python3`.

### CODE REVIEW

**Comment by LennyPhoenix** [comment]
Out of curiosity, will this affect older Mac operating systems?
As long as they can still pick up the library, this should be fine.

**Comment by jerekshoe** [comment]
> Out of curiosity, will this affect older Mac operating systems?
> As long as they can still pick up the library, this looks fine.

I tested this on a MacBook Pro running macOS 11.0 Beta 9 and a MacBook Air running macOS 10.14.6 and both worked fine, however I should mention that I only tested them with an extremely simple program

**Comment by benmoran56** [comment]
The original code was necessary at some point, but I can't say how long ago that was. It would be good to get confirmation from someone running one of the older 10.X releases as well.

I had a look at the `ctypes.util.find_library` function, and it seems that it should already be looking in the Frameworks path - at least as far back as Python 2.7. It's possible that this custom loader code was necessary on legacy python releases, as pyglet *did* support older versions than 2.7 in the past.

**Comment by ebolotin6** [comment]
Hi - any update on this?

**Comment by ebolotin6** [comment]
Hi, unfortunately this fix doesn't work for me on macOS Big Sur (11.0.1). Traceback:

`
Traceback (most recent call last):
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 84, in <module>
    from pyglet.gl.lib import GLException
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/lib.py", line 123, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='/System/Library/Frameworks/OpenGL.framework')
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/pyglet/lib.py", line 283, in load_framework
    raise ImportError("Can't find framework %s." % path)
ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    env.render()
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py", line 174, in render
    from gym.envs.classic_control import rendering
  File "/Users/ebolotin/opt/anaconda3/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    raise ImportError('''
ImportError:
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
`

**Comment by jerekshoe** [comment]
@ebolotin6 what version of python are you using? It looks like you are using an install of 3.8, which currently won't work unless you are using the version of python bundled with macOS (3.8.2, which can be found in `/usr/bin/python3`). There are still fixes that need to be made to the ctypes standard library for my modifications to work when using python 3.8 and 3.9. These changes are still in the process of being backported currently

**Comment by ebolotin6** [comment]
@jerekshoe - I am using python 3.8.3. Thanks for explaining the current situation. Looks like I'll revert back to Catalina for the time being. I don't want to mix system Python on Big Sur with a ton of packages. Let me know if you need me to test any updates in the future.

**Comment by cosmir17** [comment]
@jerekshoe use Bootcamp for a time being :)

**Comment by cosmir17** [comment]
@ebolotin6 use Bootcamp for a time being :)

**Comment by ebolotin6** [comment]
@cosmir17 - great idea regarding bootcamp!! Btw - does it work on Ubuntu?

**Comment by cosmir17** [comment]
Hi :) @ebolotin6 I changed my mind. I don't usually use a VM locally. I run an AWS instance(+ GPU) and connect it via VNC. It's working. I use 'Amazon Linux 2' Image. 

https://github.com/ponty/PyVirtualDisplay/issues/42
https://github.com/openai/baselines/issues/235
https://serverfault.com/questions/344793/install-xvfb-via-yum-yum-repository-for-xvfb

P.S. if you are interested in using VNC
https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-2-install-gui/

**Comment by jerekshoe** [comment]
@ebolotin6 the issues seen should only be with Big Sur (macOS). This code should continue to work on other OSes as it did before.

**Comment by einarf** [comment]
Works fine for me on latest Catalina.

**Review by benmoran56 — APPROVED** [review]

**Comment by benmoran56** [comment]
Thank you very much everyone for the testing, and confirmation.

**Comment by Martinnilsen99** [comment]
I am still running into this issue, running Mac OS Big Sur v11.0.1 (20B29). I am using the Python interpreter located in /usr/local/bin/python3 - Python 3.8.2 64-bit. I ran a test after reading the comment from @jerekshoe about using the bundled version, using the version located in /usr/bin/python3 - in which on my system is Python 3.7.3 64-bit. I used a virtualenv for this test, but it did not manage to locate the OpenGL Framework in this test neither.

Does someone know about a way of fixing this, getting to actually locate the right location of the framework, without downgrading to Catalina? Any help would be appreciated.

**Comment by einarf** [comment]
@Martinnilsen99 This is with 1.5.10? If so, what exact error?

**Comment by Martinnilsen99** [comment]
I get the following error, using 1.5.10:

```
>  pip freeze | grep pyglet
pyglet==1.5.10


> python agent.py -t       
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 25, in <module>
    from pyglet.gl import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyglet/gl/__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyglet/gl/lib.py", line 147, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyglet/gl/lib_agl.py", line 43, in <module>
    gl_lib = pyglet.lib.load_library(framework='OpenGL')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyglet/lib.py", line 124, in load_library
    return self.load_framework(kwargs['framework'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyglet/lib.py", line 257, in load_framework
    raise ImportError("Can't find framework %s." % name)
ImportError: Can't find framework OpenGL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "agent.py", line 236, in <module>
    argh.dispatch_command(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/argh/dispatching.py", line 306, in dispatch_command
    dispatch(parser, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "agent.py", line 167, in main
    env.render()
  File "/Users/martinnilsen/Onedrive - NTNU/Fag/Dataingeniør 3. år/Høst 2020/TDAT3025 - Anvendt maskinlæring med prosjekt/Maskinlæringsprosjekt/code/utils.py", line 76, in render
    return self.env.render(mode)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gym/core.py", line 240, in render
    return self.env.render(mode, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gym/envs/atari/atari_env.py", line 152, in render
    from gym.envs.classic_control import rendering
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    raise ImportError('''
ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
```

**Comment by einarf** [comment]
Can you try with latest python 3.9?

**Comment by jerekshoe** [comment]
@einarf this issue will persist for Big Sur users on any version of python other than the bundled one for the moment. There is currently work being done to back port all of the changes made to support Big Sur into 3.9 [PR](https://github.com/python/cpython/pull/23295) and 3.8. Until those are finished the only version of python that will work with pyglet is the 3.8.2 that should be bundled with Big Sur.

**Comment by Martinnilsen99** [comment]
@einarf @jerekshoe Do any of you know which of these being bundled with Big Sur? 

image

Seems to be having two versions of 3.8.2, and currently using the default python3 in which I believe is the one located in /usr/local/bin/python3

**Comment by cosmir17** [comment]
'Brew' pythons use path /usr/local/bin.
I think, /System/Library/ & /usr/bin/python ones are Mac bundled ones..? Please someone confirm on this.

**Comment by jerekshoe** [comment]
From what I can tell, /Library/Frameworks is the same as /usr/local/bin/python3 per [Docs](https://docs.python.org/3/using/mac.html#getting-and-installing-macpython). /System/Library/Frameworks and /usr/bin/python are the same as well (Python 2.7).  I'm not sure where the /usr/bin/python3 live however, and this is the one that is important because apple bundled a custom build with Big Sur that includes changes that aren't in any of the current python releases.

**Comment by Martinnilsen99** [comment]
@cosmir17 @jerekshoe Tried running it with the /Library/Frameworks version, and as you said its seems to be exactly the same.

**Comment by jerekshoe** [comment]
@Martinnilsen99 could you see what the output of this command is:
```
xcode-select --version
```

**Comment by Martinnilsen99** [comment]
image

**Comment by Martinnilsen99** [comment]
I did uninstall the application Xcode a few days ago, is it possible that I'm getting the error because of this? I've checked the directory tree of the framework and it's identical to the tree stated in the linked issue.

**Comment by jerekshoe** [comment]
@Martinnilsen99 if you don't mind doing some experimenting, I'd be curious to see what version you end up with if you run this:
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```
This will remove your Command Line Tools package and reinstall it. This should move you from python 3.7.3 -> 3.8.2

**Comment by jerekshoe** [comment]
See #307

**Comment by Martinnilsen99** [comment]
@jerekshoe This fixed it! Stumbled upon some problems regarding modules being placed in the path for another version, and not being able to install them somewhere else as they already existed there - but copied it from one folder to another and it worked like a charm. Thank you for the help!

**Comment by jerekshoe** [comment]
@Martinnilsen99 No problem, I'm really glad that worked for you!

**Pull request merged**
